services:
  web-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    ports:
      - 8050:8050
    depends_on:
      - callback-worker
      - query-worker
      - cache
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6379
    restart: always

  callback-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.worker
    depends_on:
      - cache
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6379
    restart: always

  query-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.worker
    command:
      [
        "celery",
        "-A",
        "app:celery_app",
        "worker",
        "--loglevel=WARNING",
        "-Q",
        "data"
      ]
    depends_on:
      - cache
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6379
    restart: always

  cache:
    image: redis
    ports:
      - 6379:6379
    restart: always
    deploy:
      resources:
        limits:
          cpus: '3.00'
          memory: 8G 
          pids: 40 
        reservations:
          cpus: '2.00'
          memory: 3G 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 8 
        window: 120s


  flower:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.flower
    depends_on:
      - callback-worker
      - query-worker
      - cache
      - web-server
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6379
    ports:
      - 5555:5555
